Parameters:
  KeyName:
    Description: Nmae of SSH access Key
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.


Resources:
################################################
#                                               VPC                                                                        #
################################################

# SeoulVPC
  SeoulVPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: 20.0.0.0/16
      Tags:
        - Key: Name
          Value: Seoul-VPC

  SeoulIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: Seoul-IGW

  SeoulVPCIGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref SeoulIGW
      VpcId: !Ref SeoulVPC


################################################
#                                               Subnet                                                                   #
################################################

# Seoul VPC public SN
  SeoulPublicSN1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SeoulVPC
      CidrBlock: 20.0.0.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
      - Key: Name
        Value: Seoul-Public-SN-1


################################################
#                                               Routing Table                                                        #
################################################

# Seoul Public SN RT
  SeoulPublicSN1RT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref SeoulVPC
      Tags:
        - Key: Name
          Value: Seoul-Public-SN-1-RT


################################################
#                                               Route                                                                     #
################################################

# Seoul VPC Route
  SeoulVPCRoute:
    Type: AWS::EC2::Route
    DependsOn: SeoulVPCIGWAttachment
    Properties:
      RouteTableId: !Ref SeoulPublicSN1RT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref SeoulIGW


################################################
#                                               VPC & RT 연결                                                        #
################################################

# public SN1 연결
  SeoulPublicSN1RouteTableAssociations:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SeoulPublicSN1
      RouteTableId: !Ref SeoulPublicSN1RT


################################################
#                                               SG                                                                           #
################################################

# AWS VPC SG
  SeoulVPCSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via Subnet
      VpcId: !Ref SeoulVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 53
        ToPort: 53
        CidrIp: 0.0.0.0/0
      - IpProtocol: udp
        FromPort: 53
        ToPort: 53
        CidrIp: 0.0.0.0/0
      - IpProtocol: icmp
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Seoul-VPC-SecurityGroup

################################################
#                                                 EC2                                                                       #
################################################

# Seoul EC2
  SeoulVPCEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09e70258ddbdf3c90
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: Seoul-VPC-EC2
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref SeoulPublicSN1
          GroupSet:
          - !Ref SeoulVPCSecurityGroup
          AssociatePublicIpAddress: true
      # UserData:
      #   Fn::Base64:
      #     !Sub |
      #       #!/bin/bash
      #       amazon-linux-extras install epel -y
      #       yum install httpd -y
      #       systemctl start httpd
      #       echo "<h1>IDC VPC Test Web Server-2</h1>" > /var/www/html/index.html
      #       yum install -y bind bind-utils bind-libs